import { test } from '@playwright/test';
import { DashboardPage } from '../pages/dashboard.page';
import { CustomersPage } from '../pages/customers.page';
import { settleDom, ensureLoggedIn } from '../lib/test-helpers';

/**
 * Generated by replaying a recorded QA-agent run — every step below is one the agent executed.
 * Goal: Go to customers page, create a client and then delete it
 */
const RUN_TAG = Math.random().toString(36).slice(2, 8);

test("Go to customers page, create a client and then delete it", async ({ page }) => {
  const dashboardPage = new DashboardPage(page);
  const customersPage = new CustomersPage(page);

  const authed = await ensureLoggedIn(page, "http://localhost:3000/dashboard", "demo", "demo123");
  if (!authed) throw new Error('Authentication failed');
  await settleDom(page);

  await dashboardPage.clickCustomersText(); // turn 1
  await customersPage.clickNewCustomerButton(); // turn 2
  await customersPage.fillNameCompanyTextbox(`Test Client ${RUN_TAG}`); // turn 3
  await customersPage.fillEmailTextbox(`test.${RUN_TAG}@example.com`); // turn 3
  await customersPage.fillPhoneTextbox("+1 650 555 0188"); // turn 3
  await customersPage.fillCompanyTextbox("Test Client Company"); // turn 3
  await customersPage.fillTitleTextbox("Director of Operations"); // turn 3
  await customersPage.fillCustomerSuccessOwnerTextbox("Jamie Lee"); // turn 3
  await customersPage.fillNotesTextbox(`Created for QA automation run ${RUN_TAG}`); // turn 3
  await customersPage.clickOkButton(); // turn 4
  await customersPage.clickDeleteButton(`Test Client ${RUN_TAG}`); // turn 5
  await customersPage.expectTextVisible(`Test Client ${RUN_TAG}`); // turn 6
  await customersPage.clickDeleteCustomerButton(); // turn 7
  await customersPage.expectTextHidden(`Test Client ${RUN_TAG}`); // turn 8
});
