import { test } from '@playwright/test';
import { ReactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page } from '../pages/react-admin-demo-use-the-left-navigation-to-go-to-team-then-back-to-customers-725e69.page';

/**
 * Use the left navigation to go to Team, then back to Customers using the navigation (not the URL bar). Verify the Custome
 * Auto-generated by Inspice — POM spec; page object lives in ../pages/react-admin-demo-use-the-left-navigation-to-go-to-team-then-back-to-customers-725e69.page.ts.
 */
test("Use the left navigation to go to Team, then back to Customers using the navigation (not the URL bar). Verify the Custome", async ({ page }) => {
  const reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page = new ReactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page(page);
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.open();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.clickButton();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible2();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.clickTeam();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible3();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible4();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible5();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.clickRoles();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible6();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible7();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible8();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.clickCustomers();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible9();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible10();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible11();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible12();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.expectVisible13();
  await reactAdminDemoUseTheLeftNavigationToGoToTeamThenBackToCustomers725e69Page.setup();
});
